---

- name: reenable node exporter service
  command: systemctl reenable prometheus-node-exporter.service

- name: reinit node exporter
  command: initctl reload-configuration

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: restart node exporter
  service:
    name: prometheus-node-exporter
    state: restarted

